version: '3.8'

services:
  user-db:
    image: mysql:8.0
    container_name: do-cu-user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - do-cu-micro-net

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    networks:
      - do-cu-micro-net

networks:
  do-cu-micro-net:
    driver: bridge